require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DrinkScanAI' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |cfg|
        cfg.build_settings['CODE_SIGNING_ALLOWED']        = 'NO'
        cfg.build_settings['CODE_SIGNING_REQUIRED']       = 'NO'
        cfg.build_settings['CODE_SIGN_IDENTITY']          = ''
        cfg.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      end
    end

    installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |config_name, config_file|
        config_file.attributes['CODE_SIGNING_ALLOWED']  = 'NO'
        config_file.attributes['CODE_SIGNING_REQUIRED'] = 'NO'
      end
    end

    # Set bridging header only for the main DrinkScanAI app target
    main_target = installer.pods_project.targets.find { |t| t.name == 'DrinkScanAI' }
    if main_target
      main_target.build_configurations.each do |cfg|
        cfg.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] = 'DrinkScanAI/DrinkScanAI-Bridging-Header.h'
      end
    end
  end
end
