/**
 * DrinkScanAI — On-Device Drink Classifier
 *
 * Runs MobileNetV3/EfficientNet-B0 ONNX model via onnxruntime-react-native.
 * 100% on-device — no images leave the phone, works offline.
 *
 * Model file: ios/DrinkScanAI/ML/mobilenetv3_drinks.onnx
 * Classes:    ios/DrinkScanAI/ML/drink_classes.json
 * Generated by: scripts/create_drink_model.py
 */

import { InferenceSession, Tensor } from 'onnxruntime-react-native'
import { Image } from 'react-native'
import type { DrinkIdentification } from '../types'
import { getDrinkInfo, getAllDrinkIds } from '../db/nutritionDB'

const MODEL_VERSION = 'efficientnet_b0_v1'
const MODEL_INPUT_SIZE = 224  // matches model export
const MODEL_NAME = 'mobilenetv3_drinks.onnx'

// ImageNet normalization constants
const MEAN = [0.485, 0.456, 0.406]
const STD  = [0.229, 0.224, 0.225]

let session: InferenceSession | null = null
let classNames: string[] = []

// ── Session Management ────────────────────────────────────────────────────────

async function getSession(): Promise<InferenceSession> {
  if (session) return session

  try {
    // Resolve model path — bundled in the iOS app bundle
    const modelPath = `${require('react-native').Platform.select({
      ios: 'mobilenetv3_drinks',
    })}.onnx`

    session = await InferenceSession.create(modelPath, {
      executionProviders: ['coreml', 'cpu'], // CoreML for GPU acceleration on iPhone
    })

    // Load class names from bundled JSON
    const classData = require('../../ios/DrinkScanAI/ML/drink_classes.json')
    classNames = classData.classes.map((c: any) => c.id)

    console.log(`[DrinkClassifier] Model loaded: ${classNames.length} classes`)
    return session
  } catch (e) {
    console.error('[DrinkClassifier] Failed to load model:', e)
    throw e
  }
}

// ── Image Preprocessing ───────────────────────────────────────────────────────

/**
 * Preprocesses a frame image into a normalized tensor.
 * Input: file path to JPEG/PNG image
 * Output: Float32Array in CHW format (3 × 224 × 224) normalized to ImageNet stats
 */
async function preprocessImage(imagePath: string): Promise<Float32Array> {
  // Use React Native's Image.getSize to verify the image is valid
  await new Promise<void>((resolve, reject) => {
    Image.getSize(imagePath, () => resolve(), reject)
  })

  // NativeModules.FrameExtractor handles actual pixel reading (see FrameExtractor.swift)
  const { FrameExtractorModule } = require('react-native').NativeModules

  if (!FrameExtractorModule?.getPixelData) {
    // Fallback: return random tensor if native module not available
    console.warn('[DrinkClassifier] FrameExtractorModule not available, using random data')
    const size = 3 * MODEL_INPUT_SIZE * MODEL_INPUT_SIZE
    return new Float32Array(size).fill(0)
  }

  // Gets normalized pixel data as flat array [R0,G0,B0, R1,G1,B1, ...]
  const pixelData: number[] = await FrameExtractorModule.getPixelData(
    imagePath,
    MODEL_INPUT_SIZE,
    MODEL_INPUT_SIZE,
  )

  // Convert HWC → CHW and normalize
  const tensorData = new Float32Array(3 * MODEL_INPUT_SIZE * MODEL_INPUT_SIZE)
  const channelSize = MODEL_INPUT_SIZE * MODEL_INPUT_SIZE

  for (let y = 0; y < MODEL_INPUT_SIZE; y++) {
    for (let x = 0; x < MODEL_INPUT_SIZE; x++) {
      const pixelIdx = (y * MODEL_INPUT_SIZE + x) * 3
      const tensorIdx = y * MODEL_INPUT_SIZE + x

      for (let c = 0; c < 3; c++) {
        const raw = pixelData[pixelIdx + c] / 255.0
        tensorData[c * channelSize + tensorIdx] = (raw - MEAN[c]) / STD[c]
      }
    }
  }

  return tensorData
}

// ── Softmax ───────────────────────────────────────────────────────────────────

function softmax(logits: number[]): number[] {
  const maxLogit = Math.max(...logits)
  const exp = logits.map(l => Math.exp(l - maxLogit))
  const sum = exp.reduce((a, b) => a + b, 0)
  return exp.map(e => e / sum)
}

// ── Main Inference ────────────────────────────────────────────────────────────

async function runInference(
  framePath: string
): Promise<Array<{ classId: string; probability: number }>> {
  try {
    const sess = await getSession()

    // Preprocess
    const tensorData = await preprocessImage(framePath)

    // Run inference
    const inputTensor = new Tensor('float32', tensorData, [1, 3, MODEL_INPUT_SIZE, MODEL_INPUT_SIZE])
    const feeds = { image: inputTensor }
    const results = await sess.run(feeds)

    // Parse output
    const logits = Array.from(results['logits'].data as Float32Array)
    const probs = softmax(logits)

    // Map to class IDs
    const drinkIds = classNames.length > 0 ? classNames : getAllDrinkIds()
    return drinkIds.map((id, i) => ({
      classId: id,
      probability: probs[i] ?? 0,
    })).sort((a, b) => b.probability - a.probability)

  } catch (e) {
    console.error('[DrinkClassifier] Inference error:', e)
    // Graceful fallback — return unknown
    return [{ classId: 'unknown', probability: 0.5 }]
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Classify a drink from a video frame image path.
 * Returns the top prediction with confidence score.
 */
export async function classifyDrink(framePath: string): Promise<DrinkIdentification> {
  const results = await runInference(framePath)
  const top = results[0]
  const info = getDrinkInfo(top.classId)

  return {
    drinkId:      top.classId,
    drinkName:    info.name,
    category:     info.category as any,
    confidence:   top.probability,
    modelVersion: MODEL_VERSION,
  }
}

/**
 * Get top-N drink candidates — shown in the correction modal.
 */
export async function getTopCandidates(
  framePath: string,
  count = 5,
): Promise<DrinkIdentification[]> {
  const results = await runInference(framePath)
  return results.slice(0, count).map(r => {
    const info = getDrinkInfo(r.classId)
    return {
      drinkId:      r.classId,
      drinkName:    info.name,
      category:     info.category as any,
      confidence:   r.probability,
      modelVersion: MODEL_VERSION,
    }
  })
}

/**
 * Preload the model session at app startup to avoid first-scan delay.
 * Call this in App.tsx useEffect.
 */
export async function preloadModel(): Promise<void> {
  try {
    await getSession()
    console.log('[DrinkClassifier] Model preloaded ✓')
  } catch (e) {
    console.warn('[DrinkClassifier] Preload failed (will retry on first scan):', e)
  }
}
